language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: "Ioan Grozea"
    branches:
      - master
      - develop
  sonarcloud:
      organization: "Ioan Grozea"
      token:
        secure: 2f3bdd2595e8ede5a2c34c403ee9f24528af2c28
notifications:
  email: false
  on_success: never
  on_failure: always
script:
  - sonar-scanner
jdk:
  - oraclejdk8
script:
  # the following command line builds the project, runs the tests with coverage and then  execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
